-- Corrige descripciones de permisos con acentos (UTF-8)
USE sicv_cecyte_bcs;

UPDATE permissions SET descripcion = 'Ver usuarios del sistema' WHERE slug = 'usuarios.read';
UPDATE permissions SET descripcion = 'Registrar nuevos usuarios' WHERE slug = 'usuarios.create';
UPDATE permissions SET descripcion = 'Editar usuarios existentes' WHERE slug = 'usuarios.update';
UPDATE permissions SET descripcion = 'Eliminar usuarios' WHERE slug = 'usuarios.delete';
UPDATE permissions SET descripcion = 'Ver vehículos' WHERE slug = 'vehiculos.read';
UPDATE permissions SET descripcion = 'Registrar vehículos' WHERE slug = 'vehiculos.create';
UPDATE permissions SET descripcion = 'Editar vehículos' WHERE slug = 'vehiculos.update';
UPDATE permissions SET descripcion = 'Dar de baja vehículos' WHERE slug = 'vehiculos.delete';
UPDATE permissions SET descripcion = 'Consultar expediente digital' WHERE slug = 'expediente.read';
UPDATE permissions SET descripcion = 'Ver comisiones' WHERE slug = 'comisiones.read';
UPDATE permissions SET descripcion = 'Registrar comisiones' WHERE slug = 'comisiones.create';
UPDATE permissions SET descripcion = 'Editar comisiones' WHERE slug = 'comisiones.update';
UPDATE permissions SET descripcion = 'Cancelar comisiones' WHERE slug = 'comisiones.delete';
UPDATE permissions SET descripcion = 'Autorizar comisiones' WHERE slug = 'comisiones.authorize';
UPDATE permissions SET descripcion = 'Ver inspecciones' WHERE slug = 'inspecciones.read';
UPDATE permissions SET descripcion = 'Registrar inspecciones' WHERE slug = 'inspecciones.create';
UPDATE permissions SET descripcion = 'Editar inspecciones' WHERE slug = 'inspecciones.update';
UPDATE permissions SET descripcion = 'Eliminar inspecciones' WHERE slug = 'inspecciones.delete';
UPDATE permissions SET descripcion = 'Ver reportes de daños' WHERE slug = 'danios.read';
UPDATE permissions SET descripcion = 'Reportar daños' WHERE slug = 'danios.create';
UPDATE permissions SET descripcion = 'Actualizar daños' WHERE slug = 'danios.update';
UPDATE permissions SET descripcion = 'Ver mantenimientos' WHERE slug = 'mantenimiento.read';
UPDATE permissions SET descripcion = 'Registrar mantenimientos' WHERE slug = 'mantenimiento.create';
UPDATE permissions SET descripcion = 'Editar mantenimientos' WHERE slug = 'mantenimiento.update';
UPDATE permissions SET descripcion = 'Autorizar mantenimientos' WHERE slug = 'mantenimiento.authorize';
UPDATE permissions SET descripcion = 'Eliminar mantenimientos' WHERE slug = 'mantenimiento.delete';
UPDATE permissions SET descripcion = 'Ver proveedores' WHERE slug = 'proveedores.read';
UPDATE permissions SET descripcion = 'Registrar proveedores' WHERE slug = 'proveedores.create';
UPDATE permissions SET descripcion = 'Editar proveedores' WHERE slug = 'proveedores.update';
UPDATE permissions SET descripcion = 'Ver catálogos (planteles, áreas, conductores y servicios)' WHERE slug = 'catalogos.read';
UPDATE permissions SET descripcion = 'Dar de alta en catálogos' WHERE slug = 'catalogos.create';
UPDATE permissions SET descripcion = 'Editar catálogos' WHERE slug = 'catalogos.update';
UPDATE permissions SET descripcion = 'Ver cargas de combustible' WHERE slug = 'combustible.read';
UPDATE permissions SET descripcion = 'Registrar cargas de combustible' WHERE slug = 'combustible.create';
UPDATE permissions SET descripcion = 'Editar cargas de combustible' WHERE slug = 'combustible.update';
UPDATE permissions SET descripcion = 'Ver herramientas del vehículo' WHERE slug = 'herramientas.read';
UPDATE permissions SET descripcion = 'Actualizar herramientas' WHERE slug = 'herramientas.update';
UPDATE permissions SET descripcion = 'Ver documentos' WHERE slug = 'documentos.read';
UPDATE permissions SET descripcion = 'Subir documentos' WHERE slug = 'documentos.create';
UPDATE permissions SET descripcion = 'Actualizar documentos' WHERE slug = 'documentos.update';
UPDATE permissions SET descripcion = 'Ver alertas' WHERE slug = 'alertas.read';
UPDATE permissions SET descripcion = 'Configurar alertas' WHERE slug = 'alertas.config';
UPDATE permissions SET descripcion = 'Ver panel principal' WHERE slug = 'dashboard.read';
UPDATE permissions SET descripcion = 'Exportar reportes' WHERE slug = 'reportes.export';
UPDATE permissions SET descripcion = 'Consultar auditoría del sistema' WHERE slug = 'auditoria.read';
